steps:
- task: DotNetCoreCLI@2
  displayName: Publish App
  inputs:
    command: publish
    publishWebProjects: false
    arguments: '-c $(buildConfiguration) -o out --no-build --no-restore'
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: AzFunction.LoL

- task: CopyFiles@2
  displayName: Copy App Output to Staging Directory
  inputs:
    sourceFolder: AzFunction.LoL/out
    contents: '**/*'
    targetFolder: $(Build.ArtifactStagingDirectory)/function

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    path: $(Build.ArtifactStagingDirectory)/function
    artifactName: Function