steps:
- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    projects: 'AzFunction.LoL.Tests/AzFunction.LoL.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'

- script: |
   dotnet tool install dotnet-reportgenerator-globaltool --tool-path .
   ./reportgenerator -reports:$(Build.SourcesDirectory)/TestResults/Coverage/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:'HtmlInline_AzurePipelines;Cobertura'
  displayName: Create Code Coverage Report

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage Report
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'